apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "model-training.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: model-training
    spec:
      restartPolicy: Never
      containers:
        - name: model-training
          image: ml-lifecycle-training:latest
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow-server.ml-lifecycle:5000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
