apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: ml-lifecycle
spec:
  type: NodePort
  selector:
    app: mlflow-server
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
