executor: LocalExecutor

airflow:
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_SECRET_ACCESS_KEY
  extraVolumeMounts:
    - name: aws-credentials
      mountPath: /root/.aws
      readOnly: true

extraVolumes:
  - name: aws-credentials
    secret:
      secretName: aws-credentials

web:
  service:
    type: NodePort
    nodePort: 30002

#workers:
#  enabled: true  # Since we're using LocalExecutor
