# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'model_exporter'
    static_configs:
      - targets: ['exporter:8000']
