apiVersion: 1

groups:
  - name: "Model Accuracy Alerts"
    interval: "1m"
    folder: "ML Alerts"
    uid: "model-accuracy-alerts-uid"
    rules:
      - alert: "LowModelAccuracy"
        uid: "low-model-accuracy-alert-uid"
        title: "Low Model Accuracy Alert"
        condition: "A"  # Correctly refers to condition A
        data:
          - refId: "A"
            queryType: "promql"
            relativeTimeRange:
              from: 3600  # 1 hour ago
              to: 0  # Present time
            datasourceUid: "PBFA97CFB590B2093"  # Your Prometheus data source UID
            model:
              expr: "avg_over_time(model_accuracy[5m])"  # Reduce to a single value using avg_over_time
        conditions:
          - evaluator:
              type: lt  # Less than
              params:
                - 0.99  # Alert if model_accuracy is less than 99%
            operator:
              type: or
            reducer:
              type: last  # Get the last reduced value to ensure a scalar output
            query:
              params:
                - "A"  # Refers to query A's reduced value
                - "5m"
                - "now"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          summary: "Model accuracy below threshold"
          description: "Model accuracy is below the acceptable threshold of 99%."
        notify:
          - name: "MailHog Email Notifications"
